import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "p-belgian-choc-tub",
    slug: "belgian-chocolate-tub",
    name: "Belgian Chocolate Tub",
    category: "tubs",
    image: "",
    price: 349,
    compareAtPrice: 399,
    size: "500ml",
    rating: 4.8,
    reviewCount: 214,
    inStock: true,
    badge: "Best Seller",
    description:
      "Rich Belgian chocolate ice cream layered with fudge swirls, made with premium cocoa.",
  },
  {
    id: "p-cookie-dough-crunch",
    slug: "cookie-dough-crunch",
    name: "Cookie Dough Crunch",
    category: "tubs",
    image: "",
    price: 375,
    size: "500ml",
    rating: 4.7,
    reviewCount: 158,
    inStock: true,
    description:
      "Vanilla ice cream loaded with chunks of chocolate chip cookie dough.",
  },
  {
    id: "p-family-fiesta-pack",
    slug: "family-fiesta-pack",
    name: "Family Fiesta Pack",
    category: "family-packs",
    image: "",
    price: 899,
    compareAtPrice: 999,
    size: "4 x 500ml",
    rating: 4.9,
    reviewCount: 96,
    inStock: true,
    badge: "20% OFF",
    description:
      "Four best-selling flavors bundled together — perfect for family gatherings.",
  },
  {
    id: "p-mango-swirl-cup",
    slug: "mango-swirl-cup",
    name: "Mango Swirl Cup",
    category: "cups",
    image: "",
    price: 99,
    size: "125ml",
    rating: 4.5,
    reviewCount: 132,
    inStock: true,
    badge: "New",
    description: "Fresh mango swirl ice cream cup, perfect for a quick treat.",
  },
  {
    id: "p-choco-almond-cone",
    slug: "choco-almond-cone",
    name: "Choco Almond Cone",
    category: "cones",
    image: "",
    price: 89,
    size: "1 cone",
    rating: 4.6,
    reviewCount: 87,
    inStock: true,
    description: "Crunchy waffle cone with chocolate almond ice cream and nut toppings.",
  },
  {
    id: "p-strawberry-cheesecake",
    slug: "strawberry-cheesecake-tub",
    name: "Strawberry Cheesecake",
    category: "tubs",
    image: "",
    price: 359,
    size: "500ml",
    rating: 4.7,
    reviewCount: 121,
    inStock: true,
    description: "Creamy cheesecake ice cream swirled with real strawberry compote.",
  },
  {
    id: "p-classic-vanilla-bar",
    slug: "classic-vanilla-bar",
    name: "Classic Vanilla Bar",
    category: "bars",
    image: "",
    price: 59,
    size: "1 bar",
    rating: 4.4,
    reviewCount: 64,
    inStock: true,
    description: "Classic vanilla ice cream bar coated in a crisp chocolate shell.",
  },
  {
    id: "p-hot-fudge-sundae",
    slug: "hot-fudge-sundae",
    name: "Hot Fudge Sundae Kit",
    category: "sundaes",
    image: "",
    price: 249,
    size: "1 kit",
    rating: 4.8,
    reviewCount: 73,
    inStock: false,
    description: "Build-your-own sundae kit with hot fudge, nuts, and cherry toppings.",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}
